import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "De plezantste mix 2026",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl" className={poppins.variable}>
      <body className="font-sans">
        <Box m={{ xs: "2em", sm: "5em 10em" }}>
          <h1 className="font-sans font-semibold text-center text-[#1E56B3] text-3xl sm:text-4xl md:text-5xl tracking-tight mb-8">
            De plezantste mix 2026
          </h1>
          {children}
        </Box>
      </body>
    </html>
  );
}
