import { prisma } from '@/lib/prisma'
import { NextResponse } from 'next/server'

export const POST = async () => {
  try {
    const songs = [
      { id: 18233, artist: 'VAT 4', title: 'E VATJE VOL BEEJ', year: 2026 },
      { id: 18199, artist: 'AZUU EN NI ANDERS', title: 'MET DE FANFARE ONDERWEG', year: 2026 },
      { id: 18215, artist: 'KJELL EN MATHIAS', title: 'DAS ONS GRUUTE MET', year: 2026 },
      { id: 18198, artist: 'APWESKILADZE EN JOHNNY WALTERS', title: 'TSEN VAN DEI ECHTE', year: 2026 },
      { id: 17955, artist: 'MATHIAS', title: 'DE NACHTWINKEL', year: 2025 },
      { id: 17735, artist: "D'HIETE PEIPERS (BLINNE EN CALLE)", title: 'NOG E LEEKE', year: 2025 },
      { id: 18204, artist: 'LESTE KANNEKES', title: 'DEN BERG AF ME A', year: 2026 },
      { id: 18208, artist: 'SMOSJTERPOTTEN', title: 'LOTJ ZE MO ZEGGE', year: 2026 },
      { id: 18219, artist: 'MC TISCHJ', title: 'DE PLON', year: 2026 },
      { id: 18218, artist: 'MATHIAS', title: 'WE GEIVE KATOON (FT MANNEN VAN DE MET)', year: 2026 },
      { id: 18213, artist: 'DJ STALPONY', title: 'VENEIR KROKET', year: 2026 },
      { id: 17702, artist: 'APWESKILADZE', title: 'ALLIEN IN ALLE FT PRINS WOUTER', year: 2025 },
      { id: 18203, artist: 'DE JONGE HEREN', title: 'GOO GETAPPISSEIT', year: 2026 },
      { id: 17945, artist: 'VERLOURE DISCJOCKEYS', title: 'EMBEKKE VERLOURE FT ANDY SMOSJ', year: 2025 },
      { id: 18200, artist: 'BOELEKE EN PISKE', title: 'EN NAA GOEME KAPOT', year: 2026 },
      { id: 18216, artist: 'LOUISKE MOUSTACHE', title: 'OP DE BIESTEMET', year: 2026 },
      { id: 18217, artist: 'DE MANNEN VAN CHIC', title: 'IK KAN MEN SLASCHE NEMI VINNE', year: 2026 },
      { id: 17682, artist: 'DE BLAAVE PLEKKERS', title: 'AAKET ALLEMOE GEWEITE', year: 2025 },
      { id: 17959, artist: 'WAAZEIJONGZEIDEGAA', title: 'WE ZEN IN ONS GAT GEBEITE (FT PRINS JOHN)', year: 2025 },
      { id: 17947, artist: 'OUDE HEREN', title: 'IK SLOAP WEIAL OP DE BANK VANNACHT', year: 2025 },
      { id: 17949, artist: 'BELLEMAN EN BELLEVRAA', title: 'DA STOPSEL (TES MISEIRE)', year: 2025 },
      { id: 18211, artist: 'DEEJAY 2AM FT FOEMP', title: 'VENEIR NOE HALLE', year: 2026 },
      { id: 18229, artist: 'TIENENTANDER', title: 'WE STEIKE T KOT IN BRAND', year: 2026 },
      { id: 18222, artist: 'JELLE', title: 'DUI DE VUI DUI', year: 2026 },
      { id: 17951, artist: 'HALLEMOE SOAME', title: 'DA GEVUUL VAN CARNAVAL', year: 2025 },
      { id: 17684, artist: 'DE JONGE HEREN', title: 'MO ZEE NAA NEKIE', year: 2025 },
      { id: 18210, artist: 'VRIE KADEIKES', title: 'ZE WAS RIBBEDEBI', year: 2026 },
      { id: 17952, artist: 'JOHNNY WALTERS', title: 'GOEME NOE DE SAUNA', year: 2025 },
      { id: 17695, artist: 'KWIK EN FLIPKE', title: 'KOM BA MAA', year: 2025 },
      { id: 17756, artist: 'LES BREUKES BOOM BOOM', title: "DON'T WORRY DER ES BIE (FT DJ ANTI)", year: 2025 },
      { id: 18234, artist: 'WAAZEIJONGZEJJEGAA', title: 'AI AI AI', year: 2026 },
      { id: 18225, artist: 'PRINS JOHN', title: 'LOTJ ZE MA ZEEN (RADIO EDIT)', year: 2026 },
      { id: 17459, artist: 'WAAZEIJONGZEIDEGAA', title: 'WOE ES MAN VRAA', year: 2024 },
      { id: 17956, artist: 'MUYLLEKES', title: 'ONDERLIJF (FT MATHIAS)', year: 2025 },
      { id: 18205, artist: 'MUYLLEKES', title: 'GEBOURE VOE CARNAVAL', year: 2026 },
      { id: 18202, artist: 'DE JEUGD VAN OUVERAL', title: 'KAMMEROETE', year: 2026 },
      { id: 15957, artist: "VAN 'T VAT", title: 'IK EM MA SKUUMA NI GEKOUZE', year: 2019 },
      { id: 17689, artist: 'FLEEREFLUITERS', title: 'REMME LOS', year: 2025 },
      { id: 17953, artist: 'DE JONGE HEREN', title: 'AAFTEMVAST', year: 2025 },
      { id: 17705, artist: 'WAAZEIJONGZEIDEGAA', title: 'IK WIL NAA E FIESJE (FT ERIC BARANYANKA)', year: 2025 },
      { id: 18230, artist: 'TISJKE PRALINE', title: 'IK EM MA', year: 2026 },
      { id: 14987, artist: 'PET RAKET EN JOHN KANON', title: 'TANTE RIET (RMX)', year: 2016 },
      { id: 17426, artist: 'AFZAKKERS', title: 'FIER OP MEN STAD', year: 2024 },
      { id: 17698, artist: 'DE PERTOTALLEKES', title: 'TAGADA (FT MANO EN WENDY)', year: 2025 },
      { id: 17439, artist: 'KWIK EN FLUPKE', title: 'ZEG DISJ HALLE', year: 2024 },
      { id: 17760, artist: 'BOELEKE EN PISKE', title: 'TERUG NO DE MET', year: 2025 },
      { id: 17124, artist: 'MC TISCHJ', title: 'IEN TWIE DRAA', year: 2023 },
      { id: 14963, artist: 'JOHNNY PURPLE', title: 'PORSELEINEN PONY', year: 2015 },
      { id: 17686, artist: 'DE MANNEN VAN DE MET', title: 'AL DEI ANNE OMUUG', year: 2025 },
      { id: 17451, artist: 'SMOSJTERPOEZEN', title: 'SMOSJTERVRAA', year: 2024 },
      { id: 17441, artist: 'DE MANNEN VAN DE MET', title: 'DAT ES 1500 (FT MATHIAS)', year: 2024 },
      { id: 12166, artist: 'ERIC DIKEB', title: 'ZEG BUUR (HOBBELEN)', year: 2010 },
      { id: 17688, artist: 'MINI EN MAXI', title: "GROESJTE FIEST VAN 'T JOER", year: 2025 },
      { id: 18224, artist: 'ONNUUZEL GEBAURE', title: 'ONNUUZEL GEBAURE (LIBERTE)', year: 2026 },
      { id: 18226, artist: 'PRINS WOUTER', title: 'CAMERA', year: 2026 },
      { id: 10086, artist: 'RONNY DE FACTEUR', title: 'ME ROESJPIEIT', year: 2009 },
      { id: 15262, artist: 'LESTE KANNEKES', title: 'STREPKE TREKKEN 2017', year: 2017 },
      { id: 17710, artist: 'DJ STALPONY', title: 'GIELEGANS KAPOT', year: 2025 },
      { id: 17761, artist: 'LAAIONHEAD STADSMUZIKANTEN', title: 'MAG DA EWA MEER ZIJN? (MET LUC EN SKILADZE)', year: 2014 },
      { id: 14907, artist: 'SJANSJEE', title: 'KOKOSNOTENDANS', year: 2016 },
      { id: 15269, artist: 'GILLES EN PIERROTS VAN GRUUT HALLE', title: 'MADE IN CHINA', year: 2017 },
      { id: 13006, artist: "VAN 'T VAT", title: "'T ES CARNAVAL", year: 2012 },
      { id: 16535, artist: 'HALLEMOE SOAME', title: 'VOESJ DOON', year: 2021 },
      { id: 17687, artist: 'DEI VAN BA CHIC', title: "ZWEMME IN D'HALSE ZENNE", year: 2025 },
      { id: 18201, artist: 'FROESJELEIRS', title: 'AS WE NOE HALLE GOEN', year: 2026 },
      { id: 12352, artist: 'LAWINEBOYS', title: "'S NACHTS NA TWEEEN", year: 2011 },
      { id: 17715, artist: 'LOUISKE MOUSTACHE', title: 'SKUUN STAD', year: 2025 },
      { id: 16210, artist: 'BELLEMAN EN BELLEVRAA', title: 'AMBIANCE EE', year: 2020 },
      { id: 18212, artist: "DEI VAN OUVER 'T WOETER", title: 'VOE ALTIJD IN MEN ET', year: 2026 },
      { id: 17382, artist: 'JOHNNY WALTERS', title: 'DEPANNAASJ (REVUE 2023)', year: 2023 },
      { id: 32534, artist: 'PRINS DITCH', title: "M'N CAMIONETTE", year: 2005 },
      { id: 16218, artist: 'HALSE DANSMARIEKES', title: 'DANS ME ONS MEI', year: 2020 },
      { id: 17452, artist: 'SMOSJTERPOTTEN', title: 'BLIJVE GOEN', year: 2024 },
      { id: 17443, artist: 'MC TISCHJ', title: 'DE FREIS', year: 2024 },
      { id: 17450, artist: 'PRINS WOUTER', title: 'DESTAG MEIRGET ONTBIJT', year: 2024 },
    ]

    const result = await prisma.song.createMany({
      data: songs,
      skipDuplicates: true,
    })

    return NextResponse.json({ success: true, inserted: result.count })
  } catch (err) {
    console.error(err)
    return NextResponse.json({ error: 'Failed to populate songs' }, { status: 500 })
  }
}
